### ISSUE TITLE
ERC-721 

### ISSUE THREAD

**Issue by patrikdevlin** [rrecuero/open-proofs#1]
Curious to how this claim can be true. In your readMe you state: `Our contract is compatible with the ERC721 Interface.` However, If you have disabled transferring of the badges, then how can this be true?

Additionally, you do not use ERC-165 to register the interface.

bytes4 private constant _InterfaceId_ERC721 = 0x80ac58cd;
  /*
   * 0x80ac58cd ===
   *   bytes4(keccak256('balanceOf(address)')) ^
   *   bytes4(keccak256('ownerOf(uint256)')) ^
   *   bytes4(keccak256('approve(address,uint256)')) ^
   *   bytes4(keccak256('getApproved(uint256)')) ^
   *   bytes4(keccak256('setApprovalForAll(address,bool)')) ^
   *   bytes4(keccak256('isApprovedForAll(address,address)')) ^
   *   bytes4(keccak256('transferFrom(address,address,uint256)')) ^
   *   bytes4(keccak256('safeTransferFrom(address,address,uint256)')) ^
   *   bytes4(keccak256('safeTransferFrom(address,address,uint256,bytes)'))
   */

**Comment by rrecuero** [comment]
Hi Patrik. We inherit the erc721 but we have disabled all the transfer functions. That's the basic assumption behind proof. You can still call balanceOf, ownerOf and the other functions from ERC721Full and ERC721Enumerable

Good point about the ERC-165 interface, we will add it.

**Comment by rrecuero** [comment]
Just to clarify, all the ERC721 functions are callable from another contract but all the transfer functions are disabled. Added support for ERC165 and clarified things in the readme. Thanks @patrikdevlin
